### ISSUE TITLE
Can't remove docker volume if lvm volume is missing

### ISSUE THREAD

**Issue by LeMyst** [containers/docker-lvm-plugin#88]
Hello,

Du to some circumstances (manual deletion), my lvm volume is now missing and I can't remove it with "docker volume rm -f".

I can do a "sudo lvcreate  -n mylvvolumedeleted -L 1 myvg" to recreate a temporary lvm volume, but a more comprehensive message than "Error response from daemon: remove mylvvolumedeleted: VolumeDriver.Remove: error removing volume" would be better, and maybe the force option remove the docker volume when the lv volume is missing (for my case).

https://github.com/containers/docker-lvm-plugin/blob/994a35e5405e50ec141300aec4645b23e8270865/utils.go#L23

**Comment by shishir-a412ed** [comment]
We already have `--force` in [`lvremove`]( https://github.com/containers/docker-lvm-plugin/blob/master/utils.go#L23)

I tried to reproduce this:

1. Create an lvm volume foobar: `docker volume create -d lvm --opt size=1G foobar`
2. docker volume ls

```
[root@fedora32 docker-lvm-plugin]# docker volume ls
DRIVER              VOLUME NAME
lvm                 foobar
```

3. Remove the underlying volume using `lvremove`: `lvremove -y vg1/foobar`

4. docker volume rm foobar

```
[root@fedora32 docker-lvm-plugin]# docker volume rm foobar
Error: No such volume: foobar
```

The error is not coming from `lvremove` but from [`here`](https://github.com/containers/docker-lvm-plugin/blob/bd6867c686e6ad4cc9b3153648d208f935e7ca04/utils.go#L153)

When you do `docker volume rm foobar`, docker first calls [`Get API`](https://github.com/containers/docker-lvm-plugin/blob/master/driver.go#L220) to get information on the volume. In the `Get` call, [`getVolumeCreationDateTime`](https://github.com/containers/docker-lvm-plugin/blob/master/driver.go#L238) is called which relies on `lvdisplay`

`lvdisplay` will fail because of the missing volume.

While I agree, the error message could be improved, this is not related to `lvremove`.
Let me see if I can add some loggers (error message) to improve debugging.
